-- All values are from a file generated by the program (your dates may be different)

-- Query 1: display all transactions for a batch (filter: merchant_id + batch_date + batch_ref_num)
SELECT t.*
FROM transactions t
JOIN batches b ON t.batch_id = b.id
WHERE b.merchant_id = 'mid0' AND b.batch_date = '2023-08-02' AND b.batch_ref_num = 'batch_ref_num0';

-- Query 2: display statistics for a batch (filter: merchant_id + batch_date + batch_ref_num)
--          grouped by transaction card type
SELECT COUNT(t.id) AS number_of_transactions, SUM(t.transaction_amount) AS total_amount
FROM transactions t
JOIN batches b ON t.batch_id = b.id
WHERE b.merchant_id = 'mid0' AND b.batch_date = '2023-08-02' AND b.batch_ref_num = 'batch_ref_num0';

-- Query 3: display top 10 merchants (by total amount) for a given date range (batch_date)
--          merchant id, merchant name, total amount, number of transactions
SELECT m.id AS merchant_id, m.name AS merchant_name, SUM(t.transaction_amount) AS total_amount, COUNT(t.id) AS number_of_transactions
FROM merchants m
JOIN batches b ON m.id = b.merchant_id
JOIN transactions t ON b.id = t.batch_id
WHERE b.batch_date BETWEEN '2023-08-02' AND '2023-08-02'
GROUP BY m.id, m.name
ORDER BY total_amount DESC
LIMIT 10;
